env:
  global:
    secure: et6v3zjYx2E6Izx7KWt63MNOzCA7CyBsDpYKQxu8u6LzFrjhCZ3Fsxr7w+CdroDg3rFJ4cjMzdF6EORoL4VavIT2Z8DrC6W/ch/8eVJgDMOdvSk3p9jzP/ET/zbc9azcRFC3wYdgp/NComiarxO1mFmtQkC7sD7SLjyhoDuH2fLFjs9sH0WdErbFJYrjmaz8tEdOuQEYEMlqYtm3mbgiHVzC2OYxOPsfONcB/yRWV0tx3q4p2URAi17QIB6GEkgwkcFgCsqU7i7OcZW9sYHUmQ987zOiQ6MdYm1Y0HsbA7nNzbYz0mi9mYMx3BKV16LlMepNEPO44RdFhbknmaylVtVvmI1r20BVYQDWD8L+zs5j7np1qSLw95NX5sBO1Lm+cme4FSdlRzVtKE1ir/Pn7744Zbnu1gMoneupTNz9zxnOFoHX8wbp1KVYzr+wDhrv6QS1JOAphCXqs6p/gGg4kzTTQnhKpnJDZJLp+4iZvzYAW70/omYLgLgrRDHc8BIHMA8EqBUDx0Y5SHiKiebX0Uww3kiFGfH+x6nb8t1GED9AI1/LjwrH0WoDMl41m5ItjdljBWJHW5qLIoUKFJhl1mCQMe9laY8+cMtGB95zV7ME/vW+EnGgl/voxSE0DW6dqI3Jo8FugKd89pXaVrCO6lb+In6EjnqHqeeovegvbyM=
language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin
install:
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" gdal==$(gdal-config --version)
  - pip install -r requirements.txt
  - pip install .
script: pytest
