language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin
install:
  - pip install gdal==`gdal-config --version`
  - pip install -r requirements.txt
  - pip install .
script: pytest