dist: bionic
addons:
  apt:
    sources:
      - ppa:ubuntugis/ppa
    packages:
    - gdal-bin
    - libgdal-dev
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install gdal==$(gdal-config --version)
  - pip install -r requirements.txt
  - pip install .
script: pytest